name: HeroBounty
version: 1.44
main: com.herocraftonline.dthielke.herobounty.HeroBountyPlugin
description: Provides a bounty system with iConomy support
commands:
  bounty:
    description:  Lists all HeroBounty commands 
    usage: /<command> help