name: HeroBounty
version: 1.9.3
author: DThielke
main: com.herocraftonline.dthielke.herobounty.HeroBounty
description: Provides a bounty system with Vault support
depend: [Vault]
commands:
  bounty:
    description:  Lists all HeroBounty commands 
    usage: /<command> help